defmodule StockExplorer.Repo.Migrations.AddCompanyAndExchange do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exchanges, primary_key: false) do
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:exchanges, [:name], name: "exchanges_unique_name_index")

    create table(:companies, primary_key: false) do
      add :exchange_id,
          references(:exchanges, column: :id, name: "companies_exchange_id_fkey", type: :uuid)

      add :ticker, :text, null: false
      add :name, :text, null: false
      add :cik, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:companies, ["ticker"])
  end

  def down do
    drop_if_exists index(:companies, ["ticker"], name: "companies_ticker_index")

    drop constraint(:companies, "companies_exchange_id_fkey")

    drop table(:companies)

    drop_if_exists unique_index(:exchanges, [:name], name: "exchanges_unique_name_index")

    drop table(:exchanges)
  end
end